server:
  port: 8080

spring:
  application:
    name: distributed-systems-homework
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 178zxc4726
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: io.github.resonxu.seckill
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    io.github.resonxu.seckill: INFO

security:
  jwt:
    secret: ReplaceWithAtLeast32CharsJwtSecretKey123456
    expiration: 7200
