server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:seckill}
    password: ${SPRING_DATASOURCE_PASSWORD:seckill123}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: io.github.resonxu.seckill
  configuration:
    map-underscore-to-camel-case: true

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}
  producer:
    group: ${ROCKETMQ_PRODUCER_GROUP:payment-service-producer-group}

seckill:
  rocketmq:
    topics:
      payment-result: ${SECKILL_ROCKETMQ_TOPIC_PAYMENT_RESULT:seckill-payment-result}

management:
  endpoints:
    web:
      exposure:
        include: health,info
